name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8'

    - name: Restore NuGet packages
      run: nuget restore aiChatterBox.sln

    - name: Build the project
      run: msbuild /p:Configuration=Release aiChatterBox.sln

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-package
        path: aiChatterBox\aiChatterBox\bin\Debug\
